<?php

use Illuminate\Database\Seeder;

class PermissoesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissoes = [
            ['nome' => 'cliente.destroy', 'nome_legivel' => 'Clientes - Excluir'],
            ['nome' => 'cliente.index', 'nome_legivel' => 'Clientes - Listar'],
            ['nome' => 'cliente.search', 'nome_legivel' => 'Clientes - Pesquisar'],
            ['nome' => 'cliente.show', 'nome_legivel' => 'Clientes - Visualizar'],
            ['nome' => 'cliente.store', 'nome_legivel' => 'Clientes - Inserir'],
            ['nome' => 'cliente.update', 'nome_legivel' => 'Clientes - Atualizar'],
            ['nome' => 'configuracao.destroy', 'nome_legivel' => 'Configurações - Excluir'],
            ['nome' => 'configuracao.index', 'nome_legivel' => 'Configurações - Listar'],
            ['nome' => 'configuracao.search', 'nome_legivel' => 'Configurações - Pesquisar'],
            ['nome' => 'configuracao.show', 'nome_legivel' => 'Configurações - Visualizar'],
            ['nome' => 'configuracao.store', 'nome_legivel' => 'Configurações - Inserir'],
            ['nome' => 'configuracao.update', 'nome_legivel' => 'Configurações - Atualizar'],
            ['nome' => 'dashboard.totais-por-situacao', 'nome_legivel' => 'Dashboard - Totais por situação'],
            ['nome' => 'dashboard.totais-por-timesheet', 'nome_legivel' => 'Dashboard - Totais por timesheet'],
            ['nome' => 'dashboard.totais-por-tipo', 'nome_legivel' => 'Dashboard - Totais por tipo'],
            ['nome' => 'equipe.destroy', 'nome_legivel' => 'Equipes - Excluir'],
            ['nome' => 'equipe.index', 'nome_legivel' => 'Equipes - Listar'],
            ['nome' => 'equipe.search', 'nome_legivel' => 'Equipes - Pesquisar'],
            ['nome' => 'equipe.show', 'nome_legivel' => 'Equipes - Visualizar'],
            ['nome' => 'equipe.store', 'nome_legivel' => 'Equipes - Inserir'],
            ['nome' => 'equipe.update', 'nome_legivel' => 'Equipes - Atualizar'],
            ['nome' => 'menu.cliente', 'nome_legivel' => 'Menu clientes'],
            ['nome' => 'menu.configuracao', 'nome_legivel' => 'Menu configurações'],
            ['nome' => 'menu.equipe', 'nome_legivel' => 'Menu equipes'],
            ['nome' => 'menu.perfil', 'nome_legivel' => 'Menu perfis'],
            ['nome' => 'menu.permissao', 'nome_legivel' => 'Menu permissões'],
            ['nome' => 'menu.projeto', 'nome_legivel' => 'Menu projetos'],
            ['nome' => 'menu.projeto-board', 'nome_legivel' => 'Menu board dos projetos'],
            ['nome' => 'menu.projeto-situacao', 'nome_legivel' => 'Menu situações de projeto'],
            ['nome' => 'menu.projeto-tipo', 'nome_legivel' => 'Menu tipos de projeto'],
            ['nome' => 'menu.relatorio', 'nome_legivel' => 'Menu dos relatórios'],
            ['nome' => 'menu.tarefa', 'nome_legivel' => 'Menu tarefas'],
            ['nome' => 'menu.tarefa-board', 'nome_legivel' => 'Menu board das tarefas'],
            ['nome' => 'menu.tarefa-situacao', 'nome_legivel' => 'Menu situações de tarefas'],
            ['nome' => 'menu.tarefa-tipo', 'nome_legivel' => 'Menu tipos de tarefas'],
            ['nome' => 'menu.usuario', 'nome_legivel' => 'Menu usuários'],
            ['nome' => 'perfil.destroy', 'nome_legivel' => 'Perfis - Excluir'],
            ['nome' => 'perfil.index', 'nome_legivel' => 'Perfis - Listar'],
            ['nome' => 'perfil.search', 'nome_legivel' => 'Perfis - Pesquisar'],
            ['nome' => 'perfil.show', 'nome_legivel' => 'Perfis - Visualizar'],
            ['nome' => 'perfil.store', 'nome_legivel' => 'Perfis - Inserir'],
            ['nome' => 'perfil.update', 'nome_legivel' => 'Perfis - Atualizar'],
            ['nome' => 'permissao.destroy', 'nome_legivel' => 'Permissões - Excluir'],
            ['nome' => 'permissao.index', 'nome_legivel' => 'Permissões - Listar'],
            ['nome' => 'permissao.search', 'nome_legivel' => 'Permissões - Pesquisar'],
            ['nome' => 'permissao.show', 'nome_legivel' => 'Permissões - Visualizar'],
            ['nome' => 'permissao.store', 'nome_legivel' => 'Permissões - Inserir'],
            ['nome' => 'permissao.update', 'nome_legivel' => 'Permissões - Atualizar'],
            ['nome' => 'pessoa.search', 'nome_legivel' => 'Pessoas - Pesquisar'],
            ['nome' => 'pessoa.show', 'nome_legivel' => 'Pessoas - Visualizar'],
            ['nome' => 'projeto.atualizar-situacao', 'nome_legivel' => 'Projetos - Atualiza situação'],
            ['nome' => 'projeto.destroy', 'nome_legivel' => 'Projetos - Excluir'],
            ['nome' => 'projeto.index', 'nome_legivel' => 'Projetos - Listar'],
            ['nome' => 'projeto.reordenar', 'nome_legivel' => 'Projetos - Reordenar'],
            ['nome' => 'projeto.search', 'nome_legivel' => 'Projetos - Pesquisar'],
            ['nome' => 'projeto.show', 'nome_legivel' => 'Projetos - Visualizar'],
            ['nome' => 'projeto-situacao.destroy', 'nome_legivel' => 'Situações dos Projetos - Excluir'],
            ['nome' => 'projeto-situacao.index', 'nome_legivel' => 'Situações dos Projetos - Listar'],
            ['nome' => 'projeto-situacao.search', 'nome_legivel' => 'Situações dos Projetos - Pesquisar'],
            ['nome' => 'projeto-situacao.show', 'nome_legivel' => 'Situações dos Projetos - Visualizar'],
            ['nome' => 'projeto-situacao.store', 'nome_legivel' => 'Situações dos Projetos - Inserir'],
            ['nome' => 'projeto-situacao.update', 'nome_legivel' => 'Situações dos Projetos - Atualizar'],
            ['nome' => 'projeto.store', 'nome_legivel' => 'Projetos - Inserir'],
            ['nome' => 'projeto-tipo.destroy', 'nome_legivel' => 'Tipos dos Projetos - Excluir'],
            ['nome' => 'projeto-tipo.index', 'nome_legivel' => 'Tipos dos Projetos - Listar'],
            ['nome' => 'projeto-tipo.search', 'nome_legivel' => 'Tipos dos Projetos - Pesquisar'],
            ['nome' => 'projeto-tipo.show', 'nome_legivel' => 'Tipos dos Projetos - Visualizar'],
            ['nome' => 'projeto-tipo.store', 'nome_legivel' => 'Tipos dos Projetos - Inserir'],
            ['nome' => 'projeto-tipo.update', 'nome_legivel' => 'Tipos dos Projetos - Atualizar'],
            ['nome' => 'projeto.update', 'nome_legivel' => 'Projetos - Atualizar'],
            ['nome' => 'relatorio.tarefas-por-periodo', 'nome_legivel' => 'Relatórios - Tarefas por período'],
            ['nome' => 'tarefa.arquivar', 'nome_legivel' => 'Tarefas - Arquivar'],
            ['nome' => 'tarefa.atualizar-situacao', 'nome_legivel' => 'Tarefas - Atualiza situação'],
            ['nome' => 'tarefa-checklist.destroy', 'nome_legivel' => 'Checklist das Tarefas - Excluir'],
            ['nome' => 'tarefa-checklist.index', 'nome_legivel' => 'Checklist das Tarefas - Listar'],
            ['nome' => 'tarefa-checklist.search', 'nome_legivel' => 'Checklist das Tarefas - Pesquisar'],
            ['nome' => 'tarefa-checklist.show', 'nome_legivel' => 'Checklist das Tarefas - Visualizar'],
            ['nome' => 'tarefa-checklist.store', 'nome_legivel' => 'Checklist das Tarefas - Inserir'],
            ['nome' => 'tarefa-checklist.update', 'nome_legivel' => 'Checklist das Tarefas - Atualizar'],
            ['nome' => 'tarefa.destroy', 'nome_legivel' => 'Tarefas - Excluir'],
            ['nome' => 'tarefa.duplicar', 'nome_legivel' => 'Tarefas - Duplicar'],
            ['nome' => 'tarefa.finalizar', 'nome_legivel' => 'Tarefas - Finalizar'],
            ['nome' => 'tarefa.index', 'nome_legivel' => 'Tarefas - Listar'],
            ['nome' => 'tarefa.iniciar', 'nome_legivel' => 'Tarefas - Iniciar'],
            ['nome' => 'tarefa.pausar', 'nome_legivel' => 'Tarefas - Pausar'],
            ['nome' => 'tarefa.reabrir', 'nome_legivel' => 'Tarefas - Reabrir'],
            ['nome' => 'tarefa.reordenar', 'nome_legivel' => 'Tarefas - Reordenar'],
            ['nome' => 'tarefa.search', 'nome_legivel' => 'Tarefas - Pesquisar'],
            ['nome' => 'tarefa.show', 'nome_legivel' => 'Tarefas - Visualizar'],
            ['nome' => 'tarefa-situacao.destroy', 'nome_legivel' => 'Situações das Tarefas - Excluir'],
            ['nome' => 'tarefa-situacao.index', 'nome_legivel' => 'Situações das Tarefas - Listar'],
            ['nome' => 'tarefa-situacao.search', 'nome_legivel' => 'Situações das Tarefas - Pesquisar'],
            ['nome' => 'tarefa-situacao.show', 'nome_legivel' => 'Situações das Tarefas - Visualizar'],
            ['nome' => 'tarefa-situacao.store', 'nome_legivel' => 'Situações das Tarefas - Inserir'],
            ['nome' => 'tarefa-situacao.update', 'nome_legivel' => 'Situações das Tarefas - Atualizar'],
            ['nome' => 'tarefa.store', 'nome_legivel' => 'Tarefas - Inserir'],
            ['nome' => 'tarefa-tipo.destroy', 'nome_legivel' => 'Tipos das Tarefas - Excluir'],
            ['nome' => 'tarefa-tipo.index', 'nome_legivel' => 'Tipos das Tarefas - Listar'],
            ['nome' => 'tarefa-tipo.search', 'nome_legivel' => 'Tipos das Tarefas - Pesquisar'],
            ['nome' => 'tarefa-tipo.show', 'nome_legivel' => 'Tipos das Tarefas - Visualizar'],
            ['nome' => 'tarefa-tipo.store', 'nome_legivel' => 'Tipos das Tarefas - Inserir'],
            ['nome' => 'tarefa-tipo.update', 'nome_legivel' => 'Tipos das Tarefas - Atualizar'],
            ['nome' => 'tarefa.update', 'nome_legivel' => 'Tarefas - Atualizar'],
            ['nome' => 'usuario.destroy', 'nome_legivel' => 'Usuários - Excluir'],
            ['nome' => 'usuario.index', 'nome_legivel' => 'Usuários - Listar'],
            ['nome' => 'usuario.search', 'nome_legivel' => 'Usuários - Pesquisar'],
            ['nome' => 'usuario.show', 'nome_legivel' => 'Usuários - Visualizar'],
            ['nome' => 'usuario.store', 'nome_legivel' => 'Usuários - Inserir'],
            ['nome' => 'usuario.update', 'nome_legivel' => 'Usuários - Atualizar'],
        ];

        foreach ($permissoes as $permissao) {
            DB::table('permissoes')->insert($permissao);
        }
    }
}
